name: [DEBIAN] Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build & Push
      run: |
        cd debian
        docker build . --file Dockerfile --tag xpot/xsa-debian:latest
        docker push xpot/xsa-debian:latest
